### ISSUE TITLE
Bug: Error when setup with Node.js v20.10.0

### ISSUE THREAD

**Issue by UsmanLiaqat404** [halbritter-lab/gene-curator#71]
Node version: `v20.10.0`

![image](https://github.com/halbritter-lab/gene-curator/assets/117591938/394af1ba-8a0c-42de-bf77-4e19caea726c)

**Comment by UsmanLiaqat404** [comment]
@berntpopp ?

**Comment by berntpopp** [comment]
Hi Usman, First thanks for your interest in this project!

It is currently in early alpha phase and only internally tested, thus I cant right now support different node versions. The one I am developing on is v16.20.0.

I will update this in the README and the upcoming Wiki, plus tets different node version in future.
